### ISSUE TITLE
No box.json, but installs OK anyway, so minor cosmetic

### ISSUE THREAD

**Issue by orcpac7** [bdw429s/FuseBox-5.1-Sample-App-Conversion#1]
CommandBox v3.0.1+00292 says:
box.json is missing so this isn't really a package! I'll install it anyway, but
I'm not happy about it
I'm just guessing what the package name, version and type are.  Please ask the p
ackage owner to add a box.json.
C:\ColdFusion2016\cfusion\wwwroot\FuseBox-5.1-Sample-App-Conversion/box.json upd
ated with dependency.

**Comment by bdw429s** [comment]
Can you send a pull request with a box.json?  Set coldbox as a dependency and set `createPackageDirectory` to `false`.   This is an older app I created back before CommandBoxing everything :)

**Comment by orcpac7** [comment]
Time for me to admit what a noob I am to collaborating with GitHub. I
created a clone in my account, orcpac7, made the edits and I thought merged
into my repo, prepping for sending you a pull request.
It appears to me though that should do it but do let me know if not.
Thanks for your patience and for all the ColdBox (CommandBox!) work you and
Louis and others have done. It's been sweet and getting sweeter!

**Comment by orcpac7** [comment]
Brad,
Please ignore or trash that pull request. Just woke up enough in the train
to try CommandBox> list in my local directory and it says package has an
invalid box.json file, but not what the problem is.
I'll look for a JSON validation tomorrow.
Regards,
Jeff D.

**Comment by bdw429s** [comment]
No worries, Jeff.  I'm out right now, but will be back later tonight. Here's a guide for creating a pull request: 
https://www.ortussolutions.com/blog/how-to-submit-pull-requests-to-the-coldbox-platform

**Comment by orcpac7** [comment]
Think it's ready.

**Comment by bdw429s** [comment]
Thanks Jeff!  Great work.

**Comment by bdw429s** [comment]
I updated the app to be compat with ColdBox and updated the readme.  The new install instructions are:

```
install bdw429s/FuseBox-5.1-Sample-App-Conversion
server start
```

Thanks again!

**Comment by orcpac7** [comment]
Thanks for the opportunity to contribute!

Now for me to go off and read how to participate in GitBook and the
documentation!
I had volunteered to edit typos in the Pre-Gitbook days for the Coldbox
2.6.3 manual but nothing ever came of that, so hoping to find participating
in that as easy to do...

**Comment by bdw429s** [comment]
The GitBooks are all stored in their own repo.  Here's the ColdBox one:
https://github.com/ColdBox/coldbox-docs

You can fork that repo and commit to it like any other repo.  Make sure you pull from upstream often though so you keep your fork in sync with the main project.  There is a desktop program you can install to edit gitbooks so you'd basically clone your fork, then point the program at that folder to edit the markdown files, then commit, push, and submit pull requests back to our `development` branch.

**Comment by orcpac7** [comment]
Installed beautifully. I see you added cbstorages dependency as part of
making it Coldbox ready.

I discovered by accident that giving it a bad mail server name throws an
unhandled exception in ColdFusion 2016, but I'm not going to raise that as
an issue as it's sample code, used to illustrate transitioning, rather than
an example of a robust Coldbox app.

Later,
JT
